Repository Vonage/vonage-laravel, pull requests merged in 2023-01, with the labels that each got.

#4 Use the 'api_secret' config field rather than 'application_id'
  src/VonageServiceProvider.php
Labels: bug, configuration error

#5 Add the "provider" argument to the publish command
  README.md
Labels: enhancement

#7 Version bumps for patch release
  README.md
  composer.json
Labels: release-candidate
